# -*- coding: utf-8 -*-
"""Module 17: Graded Mini Project_[Kaushik].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXeH4yvY-h8x7Vlz3ojzURlblM1ovk0c
"""

#importing all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#reading data from csv
df= pd.read_csv("Retail_Transactions_Dataset.csv")
df. head()

# Converting Date column
df["Date"] = pd.to_datetime(df["Date"])

# Extracting required time features
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["DayOfWeek"] = df["Date"].dt.day_name()
df.info()

#cleaning data by droping duplicates
df = df.drop_duplicates()

# Total transactions
Total_Transactions=df['Transaction_ID'].count()
print(Total_Transactions)

# Unique customers
Unique_Customers = df['Customer_Name'].nunique()
print(Unique_Customers)

# Top 5 most common products
Top_Products = df['Product'].value_counts().head(5)
print(Top_Products)

# Cities with highest number of transactions
Highest_Transaction_Cities = df['City'].value_counts()
print(Highest_Transaction_Cities)

# Average spend per customer category
Top_Customer_categories_avg= df.groupby('Customer_Category')['Total_Cost'].mean()
print(Top_Customer_categories_avg)

# Payment method preference by customer category
Preferred_Payment_Methods = df.groupby('Customer_Category')['Payment_Method'].value_counts()
print(Preferred_Payment_Methods)

# Top payment method preference by customer category
Preferred_Payment_Methods2 = Preferred_Payment_Methods.groupby(level=0).head(1)
print(Preferred_Payment_Methods2)

# Average number of items by store type
Avg_Total_Items = df.groupby("Store_Type")["Total_Items"].mean()
print(Avg_Total_Items)

# Cost of transactions where a discount was applied vs not applied
Avg_cost = df.groupby("Discount_Applied")["Total_Cost"].mean()
print(Avg_cost)

# Average number of items purchased for different promotion types
Avg_items = df.groupby("Promotion")["Total_Items"].mean()
print(Avg_items)

# Promotion with the highest total revenue
Best_promo = df.groupby("Promotion")["Total_Cost"].sum().sort_values(ascending=False)
print(Best_promo)

# Promotion that was most effective in terms of increasing total cost
promo_effectiveness = df.groupby("Promotion")["Total_Cost"].mean()
print(promo_effectiveness)

# season with the highest total revenue
Best_Season = df.groupby("Season")["Total_Cost"].sum().sort_values(ascending=False)
print(Best_Season)

# seasonal preferences for certain store types

store_type_season = df.groupby(["Store_Type", "Season"])["Total_Cost"].sum()
print(store_type_season)

store_type_season2 = df.groupby(["Season"])['Store_Type'].value_counts()
print(store_type_season2)

plt.figure(figsize=(3, 3))
sns.countplot(data=df, x="Season", hue="Store_Type")
plt.xlabel("Season")
plt.ylabel("Count")
plt.title("Store type Preference by Season")
plt.show()

# seasonal preferences for certain store types & customer categories
seasonal_preference = df.groupby(["Season", "Customer_Category","Store_Type"]).size()
print(seasonal_preference)

# plot showing average spending per season
avg_spend_season = df.groupby("Season")["Total_Cost"].mean()
plt.figure(figsize=(5, 3))
sns.barplot(x=avg_spend_season.index, y=avg_spend_season)
plt.title('Average Spending per Season')
plt.xlabel('Season')
plt.ylabel('Average Total Cost')
plt.show()

# Bar plot of number of transactions per city
transactions_per_city = df['City'].value_counts()
plt.figure(figsize=(10, 3))
sns.barplot(x=transactions_per_city.index, y=transactions_per_city)
plt.title('Number of Transactions per City')
plt.xlabel('City')
plt.ylabel('Number of Transactions')
plt.show()

# Pie chart showing distribution of payment methods
payment_method_counts = df['Payment_Method'].value_counts()
plt.figure(figsize=(5, 3))
plt.pie(payment_method_counts, labels=payment_method_counts.index, autopct='%1.1f%%')
plt.title('Distribution of Payment Methods')
plt.show()

# Line chart of monthly revenue trends
monthly_revenue = df.groupby(['Year'])['Total_Cost'].sum()
plt.figure(figsize=(10, 3))
sns.lineplot(x=monthly_revenue.index, y=monthly_revenue)
plt.title('Monthly Revenue Trends')
plt.xlabel('Year')
plt.ylabel('Total Revenue')
plt.show()

# Heatmap showing revenue by season and customer category
revenue_by_season = df.groupby(['Season', 'Customer_Category'])['Total_Cost'].sum().unstack()
plt.figure(figsize=(10, 3))
sns.heatmap(revenue_by_season, annot=True, cmap="Blues")
plt.title("Revenue by Season & Customer Category (in millions)")
plt.show()